import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from "next/font/google";
import Provider from "./provider";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata: Metadata = {
  title: "Unitip",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
