import type { Metadata } from "next";
import "./globals.css";

import { Nunito } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import Provider from "./provider";
import { ThemeProvider } from "./theme-provider";

const nunito = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata: Metadata = {
  title: "Unitip",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nunito.className} antialiased`}>
        <ThemeProvider defaultTheme="system" attribute="class">
          <Provider>
            <NextTopLoader />
            {children}
          </Provider>
        </ThemeProvider>
      </body>
    </html>
  );
}
